server:
  port: 8080
  servlet:
    session:
      cookie:
        name: MYBLOGSESSION
        http-only: true

spring:
  datasource:
    url: jdbc:h2:mem:myblog
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
